Add keyword difficulty and pla search keywords.  Include filters
silktide/semrush-api pull request #16
Opened 2017-01-10 19:09 UTC by michaelaguiar

Added two new functions, and the ability to use filters.

2017-01-10 19:15 UTC, michaelaguiar commented
Can you tell me why exactly this is failing?

2017-01-10 20:12 UTC, andywaite commented
Hey @michaelaguiar just need to update the unit tests for the changes you made.

If you click on details you can see the Travis build log.

![screenshot from 2017-01-10 20-05-43](https://cloud.githubusercontent.com/assets/6773151/21822702/383d3494-d770-11e6-9f13-523a5b9ed16a.png)

Which explains what's wrong:

![screenshot from 2017-01-10 20-06-19](https://cloud.githubusercontent.com/assets/6773151/21822730/58e4b046-d770-11e6-8f56-e657b7c1aee2.png)
 
You can also run the same tests locally, by installing PHPunit, `composer install`-ing and then running the test suite with `phpunit`.


Anyway, just need to change the 9 in `$this->assertEquals(9, count($types));` to 11 in `test/Data/TypeTest.php` and 39 in `$this->assertEquals(39, count($columns));` to 40 in `test/Data/ColumnTest.php`

To be honest, these unit tests look overkill anyway in retrospect and could possibly be removed.

2017-01-10 21:11 UTC, michaelaguiar commented
Ah I see.  Thanks for the insight!  All updated.

2017-01-11 09:59 UTC, andywaite commented on src/Client.php
> +    public function getKeywordDifficulty($phrase, $options = [])
Need to update docblock above to say $phrase

2017-01-11 10:00 UTC, andywaite requested changes
Minor thing, but one of the docbloc comments has a mistake.  Fix and we can get this merged in :D

2017-01-11 10:00 UTC, andywaite commented on src/Client.php
> +    public function getKeywordDifficulty($phrase, $options = [])
Need to update docblock above to say $phrase rather than $domain

2017-01-11 17:36 UTC, michaelaguiar commented
Oops!  All updated.  Thanks!

2017-01-11 17:37 UTC, michaelaguiar reviewed
Change made.

2017-01-11 17:39 UTC, andywaite approved these changes

2017-01-11 17:39 UTC, merged